export type AuthConfig = {
    zitadelIssuer: string;
    zitadelClientId: string;
    zitadelRedirectPath: string;
    zitadelScope: string;
};

const fallbackConfig: AuthConfig = {
    zitadelIssuer: import.meta.env.VITE_ZITADEL_ISSUER?.replace(/\/$/, '') || '',
    zitadelClientId: import.meta.env.VITE_ZITADEL_CLIENT_ID || '',
    zitadelRedirectPath: import.meta.env.VITE_ZITADEL_REDIRECT_PATH || '/auth/callback',
    zitadelScope: import.meta.env.VITE_ZITADEL_SCOPE || 'openid profile email urn:zitadel:iam:user:resourceowner',
};

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export async function loadAuthConfig(): Promise<AuthConfig> {
    for (let attempt = 1; attempt <= 20; attempt += 1) {
        try {
            const response = await fetch('/runtime/tavro-runtime-config.json', {
                cache: 'no-store',
            });

            if (response.ok) {
                const config = await response.json() as Partial<AuthConfig>;
                return {
                    ...fallbackConfig,
                    ...config,
                    zitadelIssuer: (config.zitadelIssuer || fallbackConfig.zitadelIssuer).replace(/\/$/, ''),
                };
            }
        } catch {
            // The runtime config is generated by the Docker ZITADEL configurator.
        }

        await sleep(1000);
    }

    return fallbackConfig;
}
