# syntax=docker/dockerfile:1.6
FROM debian:bookworm-slim

ARG CHIP_BINARY=third_party/collibra/chip-linux-amd64

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
    apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ${CHIP_BINARY} /app/chip

RUN chmod +x /app/chip

EXPOSE 8080

CMD ["/app/chip"]
