# =============================================================
# api/templates.py
# Industry dimension templates.
# Each template defines starter dim_nodes for:
#   process, application, technology, risk
# These are seeded when a user picks a template during setup.
# Profile, Strategy, Organisation come from AI research (public)
# or manual entry (private).
# =============================================================

from typing import Any

# ── Template node shape ───────────────────────────────────────────────────────
# { label, summary, tags, visibility, sensitive, category }

def _node(label: str, summary: str, tags: list[str],
          category: str, sensitive: bool = False) -> dict[str, Any]:
    return {
        "label":      label,
        "summary":    summary,
        "tags":       tags,
        "visibility": "internal",
        "sensitive":  sensitive,
        "category":   category,
    }


# =============================================================
# BANKING
# =============================================================
BANKING: list[dict] = [
    # ── Process ──────────────────────────────────────────────
    _node("Commercial Loan Origination",
          "End-to-end process for sourcing, underwriting, approving, and funding commercial loans above $1M. Includes credit analysis, term sheet, documentation, and closing.",
          ["loan-origination","commercial","underwriting","C&I","CRE"], "process"),
    _node("KYC / CDD Onboarding",
          "Know-Your-Customer and Customer Due Diligence process for new commercial and institutional accounts. Covers identity verification, beneficial ownership, risk scoring, and periodic review.",
          ["KYC","CDD","BSA","AML","onboarding","compliance"], "process", sensitive=True),
    _node("Credit Risk Review & Grading",
          "Quarterly review of commercial loan portfolio to assign and refresh internal risk grades (1-9 scale). Feeds the CECL allowance model and loan loss provisioning.",
          ["credit-review","CECL","risk-grading","quarterly"], "process", sensitive=True),
    _node("Deposit Account Opening",
          "Process for onboarding retail and commercial deposit customers, including treasury management product provisioning, agreement execution, and system setup.",
          ["deposits","account-opening","treasury-management","onboarding"], "process"),
    _node("Regulatory Reporting",
          "Quarterly preparation and submission of FFIEC Call Report and Federal Reserve FR Y-9C. Involves reconciliation across core banking, GL, and treasury systems.",
          ["Call-Report","FR-Y","regulatory-reporting","FFIEC","quarterly"], "process", sensitive=True),
    _node("AML Transaction Monitoring",
          "Ongoing monitoring of customer transactions against BSA/AML rules. Includes alert review, SAR filing, and OFAC sanctions screening.",
          ["AML","BSA","SAR","OFAC","transaction-monitoring"], "process", sensitive=True),
    _node("Complaint Management",
          "Intake, investigation, and resolution of customer complaints via CFPB, OCC, and direct channels. Regulated 45-day response window.",
          ["complaints","CFPB","OCC","regulatory","45-days"], "process"),

    # ── Application ───────────────────────────────────────────
    _node("Core Banking System",
          "Primary platform handling deposit accounts, general ledger, and loan servicing. Central system of record for all customer financial transactions.",
          ["core-banking","GL","deposits","loans","on-premises"], "application"),
    _node("CRM Platform",
          "Customer relationship management system for bankers and relationship officers. Tracks pipeline, activities, cross-sell opportunities, and client contacts.",
          ["CRM","pipeline","relationship","bankers","salesforce"], "application"),
    _node("Loan Origination System",
          "Cloud-based platform for commercial loan origination, credit memo, approval workflow, covenant tracking, and portfolio management.",
          ["LOS","loan-origination","cloud","commercial","covenants"], "application"),
    _node("Digital Banking Platform",
          "Online and mobile banking portal for retail and business customers. Supports account opening, payments, transfers, and account management.",
          ["digital-banking","mobile","online","retail","business-banking"], "application"),
    _node("AML / Transaction Monitoring System",
          "Platform for BSA/AML alert generation, investigation workflow, SAR filing, and sanctions screening against OFAC SDN list.",
          ["AML","BSA","Actimize","transaction-monitoring","OFAC"], "application", sensitive=True),
    _node("Enterprise Data Warehouse",
          "Cloud data warehouse consolidating feeds from core banking, CRM, LMS, and treasury systems. Primary source for management reporting and CECL modelling.",
          ["data-warehouse","EDW","Snowflake","BI","CECL","reporting"], "application"),
    _node("Risk Management Platform",
          "Integrated risk and compliance platform for enterprise risk registers, control assessments, issue tracking, and regulatory exam management.",
          ["GRC","risk","compliance","Archer","controls","regulatory"], "application", sensitive=True),

    # ── Technology ────────────────────────────────────────────
    _node("Cloud Infrastructure",
          "Hybrid or public cloud environment hosting SaaS applications and data workloads. Includes compute, storage, networking, and DR capabilities.",
          ["cloud","AWS","Azure","hybrid","infrastructure","DR"], "technology"),
    _node("API & Integration Layer",
          "Middleware platform managing integrations between core banking, CRM, LMS, and third-party systems. Supports both batch ETL and real-time API patterns.",
          ["API","integration","MuleSoft","middleware","ETL","real-time"], "technology"),
    _node("Data & Analytics Platform",
          "Analytics layer with data transformation pipelines, self-service BI dashboards, and ML model serving. Governed by enterprise data classification framework.",
          ["data","analytics","dbt","Tableau","ML","data-governance"], "technology"),
    _node("Cybersecurity Programme",
          "NIST CSF-aligned security controls including EDR, NGFW, PAM, and SIEM. Covers SOC operations, penetration testing, and vendor risk management.",
          ["cybersecurity","NIST-CSF","EDR","SIEM","SOC","vendor-risk"], "technology", sensitive=True),

    # ── Risk ─────────────────────────────────────────────────
    _node("Credit Risk — CRE Concentration",
          "Risk that commercial real estate loan concentration exceeds regulatory thresholds, triggering OCC supervisory action or capital requirements.",
          ["credit-risk","CRE","concentration","OCC","RWA"], "risk", sensitive=True),
    _node("Interest Rate Risk",
          "Risk that changes in market interest rates adversely affect net interest income or the economic value of equity. Managed via ALM model.",
          ["interest-rate","IRR","ALM","NII","NIM","duration"], "risk", sensitive=True),
    _node("BSA / AML Compliance Risk",
          "Risk of regulatory penalties or reputational harm from inadequate BSA/AML controls, deficient SAR filings, or OFAC violations.",
          ["BSA","AML","OFAC","compliance","regulatory","SAR"], "risk", sensitive=True),
    _node("Cybersecurity & Data Breach Risk",
          "Risk of unauthorised access, data exfiltration, or system disruption due to cyber threats targeting banking infrastructure or third-party vendors.",
          ["cybersecurity","data-breach","third-party","ransomware","vendor-risk"], "risk", sensitive=True),
    _node("Liquidity Risk",
          "Risk that the bank cannot meet funding obligations as they come due. Monitored via LCR, HQLA, and contingency funding plan stress tests.",
          ["liquidity","LCR","HQLA","brokered-deposits","CFP","stress-test"], "risk", sensitive=True),
    _node("Operational Risk",
          "Risk of loss from inadequate or failed internal processes, people, systems, or external events. Includes key-person dependencies and manual process failures.",
          ["operational-risk","process-failure","key-person","manual","loss-events"], "risk"),
]


# =============================================================
# INSURANCE
# =============================================================
INSURANCE: list[dict] = [
    _node("Policy Underwriting",
          "Process of evaluating insurance applications, assessing risk, pricing coverage, and issuing or declining policies.",
          ["underwriting","policy","risk-assessment","pricing"], "process"),
    _node("Claims Processing",
          "End-to-end claims intake, investigation, coverage verification, settlement, and payment. Includes fraud detection screening.",
          ["claims","settlement","fraud","FNOL","investigation"], "process"),
    _node("Actuarial Reserving",
          "Quarterly calculation of loss reserves and IBNR (incurred but not reported) estimates. Feeds statutory and GAAP financial statements.",
          ["actuarial","reserving","IBNR","statutory","GAAP"], "process", sensitive=True),
    _node("Regulatory Filing & Compliance",
          "Preparation and submission of state insurance department filings, rate filings, and annual statements.",
          ["regulatory","NAIC","state-filing","rate-filing","compliance"], "process", sensitive=True),
    _node("Agent & Broker Management",
          "Licensing, appointment, performance tracking, and commission management for independent agents and brokers.",
          ["agent","broker","distribution","commission","licensing"], "process"),
    _node("Policy Administration System",
          "Core platform for policy issuance, endorsements, renewals, cancellations, and billing.",
          ["PAS","policy-administration","billing","renewals","endorsements"], "application"),
    _node("Claims Management System",
          "Platform for FNOL, claims assignment, investigation workflow, reserve setting, and payment processing.",
          ["claims","CMS","FNOL","reserves","payments"], "application"),
    _node("Actuarial Modelling Platform",
          "Software for loss modelling, catastrophe modelling, pricing, and reserve calculations.",
          ["actuarial","catastrophe-model","pricing","reserving","R","Python"], "application"),
    _node("Document Management System",
          "Repository for policy documents, claims files, correspondence, and regulatory submissions.",
          ["DMS","documents","imaging","ECM","compliance"], "application"),
    _node("Cloud & Data Infrastructure",
          "Cloud platform supporting analytics, AI/ML workloads, and disaster recovery for insurance operations.",
          ["cloud","infrastructure","AWS","Azure","DR","analytics"], "technology"),
    _node("Analytics & Reporting Platform",
          "BI and analytics layer for loss ratios, combined ratios, agent performance, and regulatory reporting.",
          ["analytics","BI","Tableau","PowerBI","loss-ratio","reporting"], "technology"),
    _node("Cybersecurity Controls",
          "Security programme covering policyholder PII protection, SOC operations, and third-party vendor risk.",
          ["cybersecurity","PII","SOC","vendor-risk","NIST"], "technology", sensitive=True),
    _node("Catastrophe & Natural Disaster Risk",
          "Risk of large correlated losses from hurricanes, earthquakes, wildfires, or other catastrophic events.",
          ["catastrophe","CAT","hurricane","wildfire","reinsurance"], "risk", sensitive=True),
    _node("Reserve Adequacy Risk",
          "Risk that loss reserves are insufficient to cover ultimate claim costs, leading to adverse development.",
          ["reserving","IBNR","adverse-development","actuarial"], "risk", sensitive=True),
    _node("Regulatory & Solvency Risk",
          "Risk of regulatory sanctions, license revocation, or solvency impairment from inadequate capital or compliance failures.",
          ["regulatory","solvency","RBC","NAIC","compliance"], "risk", sensitive=True),
    _node("Fraud Risk",
          "Risk of financial loss from fraudulent claims, agent fraud, or application misrepresentation.",
          ["fraud","claims-fraud","SIU","detection","investigation"], "risk"),
    _node("Cyber Liability Risk",
          "Risk of policyholder data breaches or cyber incidents causing regulatory penalties and reputational harm.",
          ["cyber","data-breach","PII","regulatory-penalty","reputational"], "risk", sensitive=True),
]


# =============================================================
# HEALTHCARE
# =============================================================
HEALTHCARE: list[dict] = [
    _node("Patient Registration & Scheduling",
          "Process for new and returning patient registration, insurance verification, appointment scheduling, and pre-authorisation.",
          ["registration","scheduling","insurance-verification","pre-auth"], "process"),
    _node("Clinical Documentation & Coding",
          "Physician documentation of clinical encounters and translation into ICD-10/CPT codes for billing and quality reporting.",
          ["clinical-documentation","ICD-10","CPT","coding","EHR"], "process"),
    _node("Revenue Cycle Management",
          "End-to-end process from charge capture through claims submission, denial management, and payment posting.",
          ["RCM","billing","claims","denial-management","AR"], "process"),
    _node("Pharmacy Management",
          "Medication ordering, dispensing, reconciliation, and formulary management across care settings.",
          ["pharmacy","medication","formulary","reconciliation","dispensing"], "process"),
    _node("Quality Reporting & HEDIS",
          "Collection, validation, and submission of quality measures to CMS, payers, and accreditation bodies.",
          ["quality","HEDIS","CMS","Stars","accreditation","reporting"], "process"),
    _node("Electronic Health Record (EHR)",
          "Core clinical platform for patient records, CPOE, medication management, and clinical decision support.",
          ["EHR","Epic","Cerner","CPOE","clinical","patient-records"], "application"),
    _node("Revenue Cycle Platform",
          "System for charge capture, claims generation, clearinghouse submission, and AR management.",
          ["RCM","claims","billing","clearinghouse","AR","denials"], "application"),
    _node("Healthcare Analytics Platform",
          "Population health analytics, quality dashboards, and financial reporting across clinical and operational data.",
          ["analytics","population-health","BI","quality","reporting"], "application"),
    _node("Patient Engagement Portal",
          "Digital platform for patient communication, scheduling, test results, and telehealth.",
          ["patient-portal","telehealth","scheduling","results","engagement"], "application"),
    _node("Health IT Infrastructure",
          "Cloud and on-premises infrastructure supporting EHR, clinical applications, and data exchange.",
          ["infrastructure","cloud","HIE","HL7","FHIR","interoperability"], "technology"),
    _node("Interoperability & Data Exchange",
          "HL7 FHIR-based data exchange with payers, labs, pharmacies, and regional health information exchanges.",
          ["FHIR","HL7","HIE","interoperability","data-exchange","APIs"], "technology"),
    _node("Cybersecurity & HIPAA Controls",
          "HIPAA Security Rule compliance programme covering PHI protection, access controls, audit logging, and incident response.",
          ["cybersecurity","HIPAA","PHI","SOC","access-controls","BAA"], "technology", sensitive=True),
    _node("HIPAA Privacy & Data Breach Risk",
          "Risk of unauthorised PHI disclosure leading to OCR enforcement, breach notification, and reputational harm.",
          ["HIPAA","PHI","data-breach","OCR","privacy","notification"], "risk", sensitive=True),
    _node("Reimbursement & Payer Risk",
          "Risk that payer rate reductions, denials, or contract terminations adversely affect revenue.",
          ["reimbursement","payer","contract","denials","revenue"], "risk"),
    _node("Clinical Quality & Patient Safety Risk",
          "Risk of adverse clinical outcomes, patient safety events, or quality measure failures affecting accreditation and reimbursement.",
          ["patient-safety","quality","adverse-events","accreditation","HEDIS"], "risk"),
    _node("Ransomware & Cyber Threat Risk",
          "Risk of ransomware attacks disrupting EHR or clinical operations, a leading threat vector in healthcare.",
          ["ransomware","cybersecurity","EHR-downtime","threat","incident"], "risk", sensitive=True),
]


# =============================================================
# MANUFACTURING
# =============================================================
MANUFACTURING: list[dict] = [
    _node("Demand Planning & Forecasting",
          "Statistical and collaborative process to forecast product demand and translate it into supply chain requirements.",
          ["demand-planning","forecasting","S&OP","supply-chain"], "process"),
    _node("Production Planning & Scheduling",
          "Planning of production runs, capacity allocation, machine scheduling, and shop floor dispatch.",
          ["production","scheduling","MRP","capacity","shop-floor"], "process"),
    _node("Quality Management",
          "Incoming inspection, in-process quality control, final inspection, and non-conformance management.",
          ["quality","QC","inspection","non-conformance","ISO-9001"], "process"),
    _node("Supply Chain & Procurement",
          "Supplier selection, purchase order management, goods receipt, and supplier performance management.",
          ["supply-chain","procurement","PO","supplier","sourcing"], "process"),
    _node("Maintenance & Asset Management",
          "Preventive and corrective maintenance of production equipment, supported by CMMS and IoT sensors.",
          ["maintenance","CMMS","preventive","predictive","IoT","OEE"], "process"),
    _node("ERP System",
          "Core enterprise resource planning platform integrating finance, production, procurement, and inventory.",
          ["ERP","SAP","Oracle","finance","production","inventory"], "application"),
    _node("Manufacturing Execution System (MES)",
          "Shop floor system tracking work orders, production output, quality results, and material consumption in real time.",
          ["MES","shop-floor","work-orders","real-time","production"], "application"),
    _node("PLM / CAD Platform",
          "Product lifecycle management and engineering design tools for product development and change management.",
          ["PLM","CAD","engineering","product-design","BOM","change-management"], "application"),
    _node("Quality Management System",
          "Platform for document control, CAPA, audit management, and regulatory compliance (ISO, FDA, IATF).",
          ["QMS","CAPA","audit","ISO-9001","FDA","document-control"], "application"),
    _node("OT / Industrial Control Systems",
          "Operational technology including PLCs, SCADA, DCS, and industrial IoT platforms controlling production.",
          ["OT","SCADA","PLC","DCS","ICS","industrial-IoT"], "technology"),
    _node("IT / OT Integration",
          "Middleware and edge computing connecting shop floor OT systems to enterprise IT for data collection and analytics.",
          ["IT-OT","edge","middleware","MES-ERP-integration","connectivity"], "technology"),
    _node("Analytics & Industry 4.0 Platform",
          "Advanced analytics, machine learning, and digital twin capabilities applied to production optimisation.",
          ["Industry-4.0","analytics","ML","predictive","digital-twin","optimisation"], "technology"),
    _node("Cybersecurity — OT/IT",
          "Security programme covering both IT and OT environments, including ICS security, network segmentation, and incident response.",
          ["cybersecurity","OT-security","ICS","segmentation","NIST"], "technology", sensitive=True),
    _node("Supply Chain Disruption Risk",
          "Risk of production stoppages due to supplier failures, geopolitical events, logistics disruptions, or single-source dependencies.",
          ["supply-chain","disruption","single-source","logistics","geopolitical"], "risk"),
    _node("Product Quality & Recall Risk",
          "Risk of defective products reaching customers, triggering recalls, warranty claims, and regulatory penalties.",
          ["quality","recall","warranty","regulatory","liability"], "risk"),
    _node("OT Cyber Risk",
          "Risk of cyber attacks on industrial control systems causing production downtime, safety incidents, or physical damage.",
          ["OT","ICS","cyber","SCADA","ransomware","downtime"], "risk", sensitive=True),
    _node("Regulatory & Trade Compliance Risk",
          "Risk of non-compliance with product regulations, import/export controls, environmental standards, or labour laws.",
          ["regulatory","trade-compliance","export-control","environmental","labour"], "risk"),
]


# =============================================================
# RETAIL
# =============================================================
RETAIL: list[dict] = [
    _node("Merchandising & Assortment Planning",
          "Category-level product selection, ranging, pricing, and markdown optimisation across channels.",
          ["merchandising","assortment","pricing","markdown","category"], "process"),
    _node("Supply Chain & Replenishment",
          "Demand-driven replenishment, vendor order management, DC operations, and last-mile delivery.",
          ["supply-chain","replenishment","DC","logistics","last-mile"], "process"),
    _node("Omnichannel Order Management",
          "Unified order capture, routing, fulfilment, and returns processing across store, web, and app channels.",
          ["omnichannel","OMS","fulfilment","returns","BOPIS"], "process"),
    _node("Customer Loyalty & CRM",
          "Loyalty programme management, customer segmentation, personalisation, and CRM campaign execution.",
          ["loyalty","CRM","personalisation","segmentation","campaigns"], "process"),
    _node("Store Operations",
          "In-store processes including stock management, point-of-sale, staff scheduling, and loss prevention.",
          ["store-ops","POS","stock","scheduling","loss-prevention"], "process"),
    _node("E-Commerce Platform",
          "Digital storefront supporting product catalogue, cart, checkout, payments, and customer accounts.",
          ["e-commerce","web","app","checkout","payments","catalogue"], "application"),
    _node("POS & Store Systems",
          "Point-of-sale hardware and software, self-checkout, and in-store clienteling tools.",
          ["POS","store-systems","self-checkout","clienteling"], "application"),
    _node("Merchandising & Planning System",
          "Assortment planning, open-to-buy, allocation, and markdown optimisation platform.",
          ["merchandising","planning","allocation","markdown","open-to-buy"], "application"),
    _node("Order Management System (OMS)",
          "Unified commerce platform for order routing, inventory visibility, and fulfilment orchestration.",
          ["OMS","omnichannel","inventory","routing","fulfilment"], "application"),
    _node("Customer Data Platform (CDP)",
          "Unified customer profile platform consolidating online, in-store, and loyalty data for personalisation and analytics.",
          ["CDP","customer-data","personalisation","identity-resolution","analytics"], "application"),
    _node("Cloud & Digital Infrastructure",
          "Cloud platforms supporting e-commerce, analytics, and omnichannel capabilities at retail scale.",
          ["cloud","infrastructure","CDN","scalability","AWS","Azure"], "technology"),
    _node("Data & Personalisation Platform",
          "Real-time data processing, recommendation engines, and A/B testing infrastructure.",
          ["data","personalisation","recommendations","A/B-testing","real-time"], "technology"),
    _node("Cybersecurity & PCI Compliance",
          "Security controls for PCI DSS compliance, cardholder data protection, and e-commerce fraud prevention.",
          ["cybersecurity","PCI-DSS","fraud","cardholder-data","e-commerce"], "technology", sensitive=True),
    _node("Inventory Shrinkage & Loss Prevention Risk",
          "Risk of stock loss through theft, damage, or administrative error reducing gross margin.",
          ["shrinkage","loss-prevention","theft","ORC","inventory"], "risk"),
    _node("Supply Chain & Sourcing Risk",
          "Risk of stock-outs, margin pressure, or brand damage from supplier failures or geopolitical disruptions.",
          ["supply-chain","sourcing","stock-out","supplier","geopolitical"], "risk"),
    _node("Consumer Data & Privacy Risk",
          "Risk of customer data breaches or privacy regulation violations (CCPA, GDPR) leading to regulatory fines.",
          ["privacy","CCPA","GDPR","data-breach","customer-data"], "risk", sensitive=True),
    _node("Brand & Reputational Risk",
          "Risk of reputational harm from product safety issues, social media incidents, or ESG controversies.",
          ["brand","reputation","ESG","product-safety","social-media"], "risk"),
]


# =============================================================
# TECHNOLOGY
# =============================================================
TECHNOLOGY: list[dict] = [
    _node("Product Development & Roadmap",
          "Product discovery, prioritisation, sprint planning, and release management for software products.",
          ["product","roadmap","agile","sprint","discovery","releases"], "process"),
    _node("Software Engineering & Delivery",
          "CI/CD pipeline, code review, testing, and deployment processes for software engineering teams.",
          ["engineering","CI/CD","DevOps","testing","deployment","GitOps"], "process"),
    _node("Customer Onboarding & Success",
          "Trial, activation, onboarding, and ongoing success management for SaaS customers.",
          ["onboarding","CSM","activation","churn","NPS","success"], "process"),
    _node("Security Development Lifecycle (SDL)",
          "Secure coding practices, SAST/DAST scanning, pen testing, and vulnerability management integrated into engineering.",
          ["SDL","SAST","DAST","pen-test","vulnerability","AppSec"], "process", sensitive=True),
    _node("Incident & Reliability Management",
          "On-call, incident detection, response, post-mortem, and SLA/SLO tracking for production systems.",
          ["SRE","incident","on-call","post-mortem","SLO","reliability"], "process"),
    _node("Product & Engineering Platform",
          "Core development toolchain including source control, CI/CD, project management, and developer productivity tools.",
          ["GitHub","Jira","CI-CD","developer-platform","toolchain"], "application"),
    _node("Cloud Platform (IaaS/PaaS)",
          "Primary cloud provider infrastructure for compute, storage, databases, and managed services.",
          ["cloud","AWS","GCP","Azure","IaaS","PaaS","Kubernetes"], "application"),
    _node("CRM & Sales Platform",
          "Sales force automation, pipeline management, and customer data for go-to-market teams.",
          ["CRM","Salesforce","HubSpot","pipeline","GTM","sales"], "application"),
    _node("Data & AI Platform",
          "Data warehouse, feature store, ML training infrastructure, and model serving for AI/ML capabilities.",
          ["data","ML","AI","warehouse","feature-store","model-serving"], "application"),
    _node("Customer Support Platform",
          "Help desk, ticket management, and self-service knowledge base for customer support operations.",
          ["support","Zendesk","Intercom","tickets","KB","SLA"], "application"),
    _node("Cloud-Native Architecture",
          "Microservices, containerisation, serverless, and service mesh patterns underpinning the product platform.",
          ["cloud-native","microservices","Kubernetes","serverless","service-mesh"], "technology"),
    _node("Developer Experience & Tooling",
          "Internal developer platform, CLI tooling, documentation, and developer environment standardisation.",
          ["DevEx","IDP","developer-portal","documentation","tooling"], "technology"),
    _node("Security & Compliance Programme",
          "SOC 2, ISO 27001, or FedRAMP compliance programme covering access management, encryption, and audit logging.",
          ["SOC2","ISO-27001","FedRAMP","compliance","encryption","IAM"], "technology", sensitive=True),
    _node("AI Model & Data Governance",
          "Policies, tooling, and processes for responsible AI use, model risk management, and data lineage.",
          ["AI-governance","model-risk","data-lineage","responsible-AI","bias"], "technology"),
    _node("Security Breach & Data Exposure Risk",
          "Risk of unauthorised access to customer data, source code, or infrastructure through vulnerability exploitation.",
          ["data-breach","vulnerability","AppSec","supply-chain-attack","credentials"], "risk", sensitive=True),
    _node("Service Reliability & Downtime Risk",
          "Risk of unplanned outages or SLA breaches affecting customer retention, revenue, and reputation.",
          ["reliability","downtime","SLA","SLO","availability","outage"], "risk"),
    _node("AI & Model Risk",
          "Risk of biased, hallucinating, or non-compliant AI outputs causing customer harm or regulatory scrutiny.",
          ["AI-risk","model-risk","bias","hallucination","compliance","responsible-AI"], "risk"),
    _node("Regulatory & Data Privacy Risk",
          "Risk of GDPR, CCPA, or sector-specific regulation violations from improper data handling or cross-border transfers.",
          ["GDPR","CCPA","privacy","data-localisation","regulatory","fines"], "risk", sensitive=True),
]


# =============================================================
# BLANK (no template nodes)
# =============================================================
BLANK: list[dict] = []


# =============================================================
# Registry
# =============================================================
INDUSTRY_TEMPLATES: dict[str, list[dict]] = {
    "banking":       BANKING,
    "insurance":     INSURANCE,
    "healthcare":    HEALTHCARE,
    "manufacturing": MANUFACTURING,
    "retail":        RETAIL,
    "tech":          TECHNOLOGY,
    "blank":         BLANK,
}
