CREATE TABLE IF NOT EXISTS risk_management.agent_risk_scenarios (
  tenant_id TEXT NOT NULL,
  company_id TEXT NOT NULL,
  risk_scenario_id TEXT,
  assessment_id TEXT,
  attack_complexity_ac TEXT,
  attack_requirements_at TEXT,
  attack_vector_av TEXT,
  cvss_4_0_vector TEXT,
  agentic_ai_core_security_risks TEXT,
  privileges_required_pr TEXT,
  subsequent_system_availability_sa TEXT,
  subsequent_system_confidentiality_sc TEXT,
  subsequent_system_integrity_si TEXT,
  created_ts TIMESTAMP,
  updated_ts TIMESTAMP,
  user_interaction_ui TEXT,
  vulnerable_system_availability_va TEXT,
  vulnerable_system_confidentiality_vc TEXT,
  vulnerable_system_integrity_vi TEXT,
  created_by TEXT,
  updated_by TEXT,
  threat_multiplier DECIMAL(10, 2),
  cvss_score DECIMAL(10, 2),
  aivss_score DECIMAL(10, 2),
  CONSTRAINT chk_agent_risk_scenarios_tenant_id_present CHECK (tenant_id IS NOT NULL AND btrim(tenant_id) <> ''),
  CONSTRAINT chk_agent_risk_scenarios_company_id_present CHECK (company_id IS NOT NULL AND btrim(company_id) <> '')
);
