CREATE TABLE IF NOT EXISTS risk_management.agent_risk_assessment (
  tenant_id TEXT,
  company_id TEXT,
  agent_name TEXT,
  agent_risk_assessment_name TEXT,
  analysis_requested_at timestamp,
  assessor TEXT,
  audit TEXT,
  autonomy_of_action_rationale TEXT,
  bias_classification_rationale TEXT,
  comments TEXT,
  contextual_awareness_rationale TEXT,
  dynamic_identity_rationale TEXT,
  dynamic_tool_use_rationale TEXT,
  eu_ai_act_article_5_prohibited_ai_practices_evaluation TEXT,
  eu_ai_act_article_6_high_risk_ai_systems_evaluation TEXT,
  goal_driven_planning_rationale TEXT,
  memory_use_rationale TEXT,
  multi_agent_interactions_rationale TEXT,
  non_determinism_rationale TEXT,
  opacity_reflexivity_rationale TEXT,
  payment_card_industry TEXT,
  personally_identifiable_information TEXT,
  protected_health_information TEXT,
  risk_classification TEXT,
  risk_classification_analyzed timestamp,
  risk_classification_rationale TEXT,
  self_modification_rationale TEXT,
  state TEXT,
  summary TEXT,
  type_of_risk TEXT,
  updated_ts timestamp,
  created_ts timestamp,
  created_by TEXT,
  updated_by TEXT,
  assessment_id TEXT,
  agent_id TEXT,
  aars_score decimal(10, 2),
  ai_vulnerability_scoring_system_aivss_weighting decimal(10, 2),
  aivss_score decimal(10, 2),
  autonomy_of_action decimal(10, 2),
  bias_risk decimal(10, 2),
  contextual_awareness decimal(10, 2),
  cvss_score decimal(10, 2),
  dynamic_identity decimal(10, 2),
  dynamic_tool_use decimal(10, 2),
  goal_driven_planning decimal(10, 2),
  memory_use decimal(10, 2),
  multi_agent_interactions decimal(10, 2),
  non_determinism decimal(10, 2),
  regulatory_risk_weighting decimal(10, 2),
  risk_classification_score decimal(10, 2),
  self_modification decimal(10, 2),
  opacity_reflexivity decimal(10, 2),
  blended_risk_score decimal(10, 2),
  agent_internal_id TEXT);
