/**
 * Single source of truth for the Tavro PDF document template.
 *
 * Typography and layout values (font sizes, Y positions, heights) are read from
 * the <!-- pdf-visual-config --> block in pdf-document-template.md so that a
 * single edit to that file propagates to every PDF generated by the platform.
 *
 * Brand colors remain here — they are design constants, not admin-configurable.
 *
 * The copilot server (server.js) reads the same .md file at runtime.
 * When the template changes, update only that .md file — no other edits needed.
 */

// Vite ?raw import — bundles the .md file contents as a string at build time.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import templateContent from '../../copilot-server/templates/pdf-document-template.md?raw';

export type PdfRgb = [number, number, number];

export interface PdfVisualFormat {
  headerHeight: number;
  headerBackground: PdfRgb;
  headerBorder: PdfRgb;
  accent: PdfRgb;
  accentHeight: number;
  nameColor: PdfRgb;
  nameSize: number;
  nameY: number;
  typeColor: PdfRgb;
  typeSize: number;
  typeY: number;
  subtitleColor: PdfRgb;
  subtitleSize: number;
  subtitleY: number;
  dateColor: PdfRgb;
  dateSize: number;
  dateY: number;
  footerBackground: PdfRgb;
  footerBorder: PdfRgb;
  footerText: PdfRgb;
  footerHeight: number;
  contentStartY: number;
}

/** Parse the <!-- pdf-visual-config ... --> block from the master template. */
function parsePdfVisualConfig(md: string): Partial<Record<string, number>> {
  const match = md.match(/<!--\s*pdf-visual-config\s*\n([\s\S]+?)\n-->/);
  if (!match) return {};
  try {
    return JSON.parse(match[1]) as Partial<Record<string, number>>;
  } catch {
    return {};
  }
}

const _cfg = parsePdfVisualConfig(templateContent as string);

const _n = (key: string, fallback: number): number =>
  typeof _cfg[key] === 'number' ? (_cfg[key] as number) : fallback;

export const PDF_VISUAL_FORMAT: PdfVisualFormat = {
  // Brand colors — defined in code, not in the template config
  headerBackground: [255, 255, 255],
  headerBorder:     [226, 232, 240],
  accent:           [203, 213, 225],
  nameColor:        [30, 41, 59],
  typeColor:        [71, 85, 105],
  subtitleColor:    [100, 116, 139],
  dateColor:        [100, 116, 139],
  footerBackground: [248, 250, 252],
  footerBorder:     [226, 232, 240],
  footerText:       [148, 163, 184],
  // Typography and layout — sourced from pdf-document-template.md
  headerHeight:  _n('headerHeight',  44),
  accentHeight:  _n('accentHeight',  1.5),
  nameSize:      _n('nameSize',      11),
  nameY:         _n('nameY',         17),
  typeSize:      _n('typeSize',      8),
  typeY:         _n('typeY',         23),
  subtitleSize:  _n('subtitleSize',  7.5),
  subtitleY:     _n('subtitleY',     29),
  dateSize:      _n('dateSize',      7),
  dateY:         _n('dateY',         29),
  footerHeight:  _n('footerHeight',  12),
  contentStartY: _n('contentStartY', 50),
};

export const PDF_DOCUMENT_TEMPLATE: string = templateContent as string;
