CREATE TABLE IF NOT EXISTS core.agents (
	tenant_id TEXT NOT NULL,
	agent_source_id TEXT,
	agent_name TEXT,
	agent_description TEXT,
	protocol_version TEXT,
	preferred_transport TEXT,
	supports_auth_ext_card boolean,
	card_version TEXT,
	source_hash TEXT,
	source_system TEXT,
	record_hash TEXT,
	valid_from_ts timestamp,
	valid_to_ts timestamp,
	is_current boolean,
	created_ts timestamp,
	updated_ts timestamp,
	agent_id TEXT,
	parent_agent_id TEXT,
	company_id TEXT NOT NULL,
	company_name TEXT,
	agent_type TEXT DEFAULT 'Config-driven',
	status TEXT DEFAULT 'Plan',
	CONSTRAINT chk_agents_tenant_id_present CHECK (tenant_id IS NOT NULL AND btrim(tenant_id) <> ''),
	CONSTRAINT chk_agents_company_id_present CHECK (company_id IS NOT NULL AND btrim(company_id) <> ''),
	CONSTRAINT pk_core_agents PRIMARY KEY (tenant_id, company_id, agent_id)
);
