CREATE TABLE IF NOT EXISTS core.agent_identifications (
  tenant_id TEXT NOT NULL,
  company_id TEXT NOT NULL,
  agent_source_id TEXT,
  goal_orientation TEXT,
  role TEXT,
  instruction TEXT,
  owner TEXT,
  environment TEXT,
  tags TEXT[],
  governance_status TEXT,
  reviewer TEXT,
  cost_center TEXT,
  is_current boolean,
  created_ts timestamp,
  updated_ts timestamp,
  agent_id TEXT,
  CONSTRAINT chk_agent_identifications_tenant_id_present CHECK (tenant_id IS NOT NULL AND btrim(tenant_id) <> ''),
  CONSTRAINT chk_agent_identifications_company_id_present CHECK (company_id IS NOT NULL AND btrim(company_id) <> '')
);
