CREATE TABLE IF NOT EXISTS core.agent_knowledge_sources (
  tenant_id TEXT NOT NULL,
  company_id TEXT NOT NULL,
  agent_source_id TEXT,
  identifier TEXT,
  name TEXT,
  access_mechanism TEXT,
  description TEXT,
  source_type TEXT,
  connection_string TEXT,
  format TEXT,
  refresh_frequency TEXT,
  is_sensitive boolean,
  owner TEXT,
  status TEXT,
  created_ts timestamp,
  updated_ts timestamp,
  agent_id TEXT,
  CONSTRAINT chk_agent_knowledge_sources_tenant_id_present CHECK (tenant_id IS NOT NULL AND btrim(tenant_id) <> ''),
  CONSTRAINT chk_agent_knowledge_sources_company_id_present CHECK (company_id IS NOT NULL AND btrim(company_id) <> '')
);
