CREATE TABLE IF NOT EXISTS core.ai_use_cases (
  tenant_id TEXT,
  ai_use_case_id TEXT,
  name TEXT,
  description TEXT,
  proposed_by TEXT,
  owner TEXT,
  function TEXT,
  problem_statement TEXT,
  expected_benefits TEXT,
  priority TEXT,
  status TEXT,
  created_ts timestamp,
  updated_ts timestamp,
  agent_risk_exposure_are decimal(10, 2),
  no_of_associated_agents int,
  inherent_risk_classification TEXT,
  residual_risk_classification TEXT,
  agent_risk_tier_art TEXT,
  blended_risk_score decimal(10, 2),
  inherent_risk_classification_score decimal(10, 2),
  residual_risk_classification_score decimal(10, 2),
  solution_approach TEXT,
  company_id TEXT,
  company_name TEXT,
  assumptions TEXT,
  quantified_financial_benefits TEXT,
  total_financial_impact_summary TEXT,
  implementation_cost_estimate TEXT,
  return_on_investment TEXT,
  risk_considerations TEXT,
  implementation_roadmap TEXT,
  recommendation TEXT,
  executive_summary TEXT,
  business_value_score                  INTEGER CHECK (business_value_score BETWEEN 1 AND 5),
  business_value_override               BOOLEAN DEFAULT FALSE,
  business_value_override_reason        TEXT,
  data_readiness_score                  INTEGER CHECK (data_readiness_score BETWEEN 1 AND 5),
  data_readiness_override               BOOLEAN DEFAULT FALSE,
  data_readiness_override_reason        TEXT,
  technical_complexity_score            INTEGER CHECK (technical_complexity_score BETWEEN 1 AND 5),
  technical_complexity_override         BOOLEAN DEFAULT FALSE,
  technical_complexity_override_reason  TEXT,
  risk_data_privacy_score               INTEGER CHECK (risk_data_privacy_score BETWEEN 1 AND 5),
  risk_operational_score                INTEGER CHECK (risk_operational_score BETWEEN 1 AND 5),
  risk_compliance_score                 INTEGER CHECK (risk_compliance_score BETWEEN 1 AND 5),
  risk_ai_behavioral_score              INTEGER CHECK (risk_ai_behavioral_score BETWEEN 1 AND 5),
  risk_strategic_reputational_score     INTEGER CHECK (risk_strategic_reputational_score BETWEEN 1 AND 5),
  risk_composite_score                  DECIMAL(4, 2),
  priority_score                        DECIMAL(4, 2),
  quadrant                              TEXT CHECK (quadrant IN ('quick_win', 'big_bet', 'fill_in', 'money_pit')),
  time_horizon                          TEXT CHECK (time_horizon IN ('now', 'next', 'later')),
  time_horizon_rationale                TEXT,
  roadmap_approved                      BOOLEAN DEFAULT FALSE,
  scoring_history                       JSONB DEFAULT '[]'::JSONB
);

