CREATE TABLE IF NOT EXISTS core.business_integrations (
    integration_id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    integration_name TEXT,
    integration_description TEXT,
    capabilities TEXT,
    protocol TEXT,
    endpoint_url TEXT,
    authentication_method TEXT,
    owner TEXT,
    documentation_url TEXT,
    data_sensitivity TEXT,
    rate_limit TEXT,
    availability_status TEXT,
    sla TEXT,
    version TEXT,
    parent_application_id TEXT,
    company_id TEXT NOT NULL,
    company_name TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    business_criticality TEXT,
    emergency_tier TEXT,
    blended_risk_score NUMERIC,
    agent_risk_exposure NUMERIC,
    agent_risk_tier TEXT,
    inherent_risk_classification TEXT,
    residual_risk_classification TEXT,
    inherent_risk_classification_score NUMERIC,
    residual_risk_classification_score NUMERIC,
    num_of_associated_agents INTEGER,
    sensitive BOOLEAN DEFAULT FALSE,
    visibility TEXT DEFAULT 'internal',
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    created_ts TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_ts TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_business_integrations_tenant_id_present CHECK (tenant_id IS NOT NULL AND btrim(tenant_id) <> ''),
    CONSTRAINT chk_business_integrations_company_id_present CHECK (company_id IS NOT NULL AND btrim(company_id) <> ''),
    CONSTRAINT ux_core_business_integrations_tenant_company UNIQUE (tenant_id, company_id, integration_id)
);
