CREATE TABLE IF NOT EXISTS core.business_applications (
    tenant_id TEXT,
    business_application_id TEXT,
    application_name TEXT,
    emergency_tier TEXT,
    business_owner TEXT,
    application_portfolio_manager TEXT,
    vendor_name TEXT,
    business_criticality TEXT,
    it_application_owner TEXT,
    application_description TEXT,
    agent_risk_exposure DOUBLE PRECISION,
    num_of_associated_agents INTEGER,
    inherent_risk_classification TEXT,
    residual_risk_classification TEXT,
    agent_risk_tier TEXT,
    blended_risk_score DOUBLE PRECISION,
    inherent_risk_classification_score DOUBLE PRECISION,
    residual_risk_classification_score DOUBLE PRECISION,
    embedded_ai TEXT,
    opt_out_option TEXT,
    privacy_policy_url TEXT,
    data_excluded_from_ai_training TEXT,
    vendor_description TEXT,
    current_installed_version TEXT,
    is_current_version_supported TEXT,
    latest_released_version TEXT,
    latest_release_date TEXT,
    latest_release_documentation_link TEXT,
    company_id TEXT,
    company_name TEXT,
    created_ts TIMESTAMP,
    updated_ts TIMESTAMP
);
