CREATE TABLE IF NOT EXISTS core.business_processes (
    tenant_id TEXT NOT NULL,
    business_process_id TEXT,
    process_number TEXT,
    process_name TEXT,
    process_description TEXT,
    parent_process_id TEXT,
    owner TEXT,
    stakeholders TEXT,
    operators TEXT,
    business_criticality TEXT,
    reputational_impact TEXT,
    num_of_associated_agents INTEGER,
    agent_risk_tier TEXT,
    residual_risk_classification TEXT,
    inherent_risk_classification TEXT,
    financial_impact TEXT,
    regulatory_impact TEXT,
    agent_risk_exposure DOUBLE PRECISION,
    blended_risk_score DOUBLE PRECISION,
    residual_risk_classification_score DOUBLE PRECISION,
    inherent_risk_classification_score DOUBLE PRECISION,
    sla TEXT,
    process_health_state TEXT,
    company_id TEXT NOT NULL,
    company_name TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    sensitive BOOLEAN DEFAULT FALSE,
    visibility TEXT DEFAULT 'internal',
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    created_ts TIMESTAMP,
    updated_ts TIMESTAMP,
    CONSTRAINT chk_business_processes_tenant_id_present CHECK (tenant_id IS NOT NULL AND btrim(tenant_id) <> ''),
    CONSTRAINT chk_business_processes_company_id_present CHECK (company_id IS NOT NULL AND btrim(company_id) <> ''),
    CONSTRAINT pk_core_business_processes PRIMARY KEY (tenant_id, company_id, business_process_id)
);
