CREATE TABLE IF NOT EXISTS core.business_integrations (
    integration_id TEXT PRIMARY KEY,
    tenant_id TEXT,
    integration_name TEXT,
    integration_description TEXT,
    capabilities TEXT,
    protocol TEXT,
    endpoint_url TEXT,
    authentication_method TEXT,
    owner TEXT,
    documentation_url TEXT,
    data_sensitivity TEXT,
    rate_limit TEXT,
    availability_status TEXT,
    sla TEXT,
    version TEXT,
    parent_application_id TEXT,
    company_id TEXT,
    company_name TEXT,
    business_criticality TEXT,
    emergency_tier TEXT,
    blended_risk_score NUMERIC,
    agent_risk_exposure NUMERIC,
    agent_risk_tier TEXT,
    inherent_risk_classification TEXT,
    residual_risk_classification TEXT,
    inherent_risk_classification_score NUMERIC,
    residual_risk_classification_score NUMERIC,
    num_of_associated_agents INTEGER,
    created_ts TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_ts TIMESTAMPTZ NOT NULL DEFAULT now()
);
